// Mock data for development - properties for rent and sale
export const mockProperties = [
  // FOR SALE
  {
    id: '1',
    title: 'Luxury Villa in Santorini',
    description: 'Stunning white-washed villa with caldera views, perfect for a vacation home or investment',
    price: 1500000,
    address: 'Oia Road 123',
    city: 'Santorini',
    region: 'South Aegean',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1570077189670-ba3e7458af70?w=800',
    listingType: 'sale',
    propertyType: 'villa',
    area: 350,
    bedrooms: 4,
    bathrooms: 3,
    yearBuilt: 2018,
  },
  {
    id: '2',
    title: 'Modern Apartment in Mykonos',
    description: 'Contemporary apartment in the heart of Mykonos town, ideal for living or seasonal rental',
    price: 850000,
    address: 'Main Street 456',
    city: 'Mykonos',
    region: 'South Aegean',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1567971502209-56b08ee278d7?w=800',
    listingType: 'sale',
    propertyType: 'apartment',
    area: 120,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2020,
  },
  {
    id: '3',
    title: 'Traditional House in Crete',
    description: 'Charming traditional stone house in the Cretan countryside with olive grove',
    price: 450000,
    address: 'Village Road 789',
    city: 'Chania',
    region: 'Crete',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1570129477492-45ec003aafea?w=800',
    listingType: 'sale',
    propertyType: 'house',
    area: 200,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 1995,
  },
  
  // FOR RENT
  {
    id: '4',
    title: 'Cozy Studio Apartment - Athens',
    description: 'Perfect starter apartment in central Athens, close to metro and shops',
    price: 800,
    address: 'Syntagma 321',
    city: 'Athens',
    region: 'Attica',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    listingType: 'rent',
    propertyType: 'studio',
    area: 45,
    bedrooms: 0,
    bathrooms: 1,
    yearBuilt: 2015,
  },
  {
    id: '5',
    title: 'Beachfront Villa - Crete',
    description: 'Beautiful beachfront villa with direct beach access, perfect for summer vacations',
    price: 2500,
    address: 'Beach Road 111',
    city: 'Heraklion',
    region: 'Crete',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1570129477492-45ec003aafea?w=800',
    listingType: 'rent',
    propertyType: 'villa',
    area: 300,
    bedrooms: 5,
    bathrooms: 4,
    yearBuilt: 2019,
  },
  {
    id: '6',
    title: 'Modern Apartment - Thessaloniki',
    description: 'Spacious modern apartment with all amenities, near the waterfront',
    price: 1200,
    address: 'Waterfront Ave 555',
    city: 'Thessaloniki',
    region: 'Central Macedonia',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    listingType: 'rent',
    propertyType: 'apartment',
    area: 140,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 2021,
  },
  {
    id: '7',
    title: 'Family House - Peloponnese',
    description: 'Spacious family home perfect for long-term rent, great for families',
    price: 1500,
    address: 'Mountain View 222',
    city: 'Nafplio',
    region: 'Peloponnese',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1570129477492-45ec003aafea?w=800',
    listingType: 'rent',
    propertyType: 'house',
    area: 250,
    bedrooms: 4,
    bathrooms: 3,
    yearBuilt: 2010,
  },
  {
    id: '8',
    title: 'Seaside House in Rethymno, Crete',
    description: 'Beautiful coastal house with sea views and private patio, perfect for a Mediterranean lifestyle',
    price: 650000,
    address: 'Coastal Street 456',
    city: 'Rethymno',
    region: 'Crete',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    listingType: 'sale',
    propertyType: 'house',
    area: 280,
    bedrooms: 4,
    bathrooms: 3,
    yearBuilt: 2005,
  },
  {
    id: '9',
    title: 'Charming Cretan House for Rent',
    description: 'Authentic Cretan stone house with traditional architecture and modern amenities, ideal for long-term rental',
    price: 1800,
    address: 'Old Town Lane 789',
    city: 'Heraklion',
    region: 'Crete',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1512917774080-9b274b3057d5?w=800',
    listingType: 'rent',
    propertyType: 'house',
    area: 220,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 2012,
  },
];
